export const dummyChats = [
    {
        id: '1',
        username: '최영호 주임님',
        profile: 'https://avatar.iran.liara.run/public/49',
        messages: [
            {
                id: '1',
                text: '안녕하세요 주임님, 기간이 촉박하여 먼저 연락드립니다!',
                sender: 'other',
                time: '14:30',
                isRead: true,
            },
            {
                id: '2',
                text: '네, 안녕하세요. 무슨 일이신가요?',
                sender: 'me',
                time: '14:31',
                isRead: true,
            },
            {
                id: '3',
                image: 'https://picsum.photos/400/300',
                sender: 'other',
                time: '14:32',
                isRead: true,
            },
            {
                id: '4',
                audio: 'https://www.learningcontainer.com/wp-content/uploads/2020/02/Kalimba.mp3',
                sender: 'other',
                time: '14:35',
                isRead: true,
            },
            {
                id: '5',
                text: '프로젝트 관련 파일 보내드렸어요. 확인 부탁드립니다.',
                sender: 'other',
                time: '14:32',
                isRead: true,
            },
            {
                id: '6',
                text: '네, 확인해보겠습니다. 잠시만 기다려주세요.',
                sender: 'me',
                time: '14:33',
                isRead: true,
            },
            {
                id: '7',
                audio: 'https://www.learningcontainer.com/wp-content/uploads/2020/02/Kalimba.mp3',
                sender: 'me',
                time: '14:35',
                isRead: false,
            },
            {
                id: '8',
                text: '음성 메시지로 설명을 드렸습니다. 들어보시고 논의 사항 있으시면 편하게 말씀해주세요.',
                sender: 'me',
                time: '14:35',
                isRead: false,
            },
        ],
    },
    {
        id: '2',
        username: 'Boreplay 박지영',
        profile: 'https://avatar.iran.liara.run/public/86',
        messages: [
            {
                id: '1',
                text: '프로젝트의 진행 상황 어떻게 되고 있나요?',
                sender: 'me',
                time: '12:25',
                isRead: true,
            },
            {
                id: '2',
                text: '현재 디자인 단계에 있습니다. 다음 주까지 완료할 예정입니다.',
                sender: 'other',
                time: '12:27',
                isRead: true,
            },
        ],
    },
    {
        id: '3',
        username: '한국외국어대학교',
        profile: 'https://picsum.photos/200/300?image=945',
        messages: [
            {
                id: '1',
                text: `안녕하세요. 한국외국어대학교에서 공지 드립니다. 공지부서 : AI교육원, 공지내용 : 2024학년도 1학기 여름방학 코딩테스트 대비 캠프 참가자 모집\n
1. 신청 기간 : ~ 2024. 7. 15(월)\n2. 신청 방법 : 구글 설문으로 신청서 작성 → https://forms.gle/WKhX3gq9Vpneu1Gy7\n
3. 선발 방법 : 선행 필요 지식 등을 고려해 초급반 60명, 중급반 60명 내외 선발\n
▶자세한 사항은 AI교육원 홈페이지 참조바랍니다.\nhttps://soft.hufs.ac.kr/`,
                sender: 'other',
                time: '09:10',
                isRead: true,
            },
        ],
    },
    {
        id: '4',
        username: '배민주',
        profile: 'https://avatar.iran.liara.run/public/40',
        messages: [
            { id: '1', text: '점심 뭐 드실래요?', sender: 'other', time: '11:45', isRead: true },
            { id: '2', text: '피자 어때요?', sender: 'me', time: '11:50', isRead: true },
            {
                id: '3',
                text: '피자 맛집을 아는데 거기 가실래요?',
                sender: 'other',
                time: '11:52',
                isRead: true,
            },
            {
                id: '4',
                text: '좋아요! 점심 피맥하러 가죠 🍕',
                sender: 'me',
                time: '11:55',
                isRead: true,
            },
        ],
    },
    {
        id: '5',
        username: '방구쟁이',
        profile: 'https://avatar.iran.liara.run/public/77',
        messages: [
            {
                id: '1',
                text: '이번 주말에 등산 가자',
                sender: 'other',
                time: '10:30',
                isRead: true,
            },
            { id: '2', text: '헉 등산...', sender: 'me', time: '10:35', isRead: true },
            {
                id: '3',
                text: '우리 동네 산 좋아',
                sender: 'other',
                time: '10:40',
                isRead: true,
            },
            { id: '4', text: '등산은 무리데스...', sender: 'me', time: '10:42', isRead: true },
            {
                id: '4',
                text: '눈물이 나......',
                sender: 'other',
                time: '10:40',
                isRead: true,
            },
        ],
    },
    {
        id: '6',
        username: '김민지',
        profile: 'https://picsum.photos/id/6/200',
        messages: [
            {
                id: '1',
                text: '오늘 회의록 작성해뒀습니다!',
                sender: 'other',
                time: '15:12',
                isRead: true,
            },
            {
                id: '2',
                text: '넵 감사합니다!',
                sender: 'me',
                time: '15:15',
                isRead: true,
            },
        ],
    },
    {
        id: '7',
        username: '이용우',
        profile: 'https://avatar.iran.liara.run/public/41',
        messages: [
            {
                id: '1',
                text: '이번 주말에 여행 가고 싶은데 추천지 좀',
                sender: 'other',
                time: '13:20',
                isRead: true,
            },
            { id: '2', text: '어디로 가고싶은데?', sender: 'me', time: '13:25', isRead: true },
            {
                id: '3',
                text: '음..이왕이면 바다?',
                sender: 'other',
                time: '13:30',
                isRead: true,
            },
            {
                id: '4',
                text: '그럼 부산 ㄱㄱ',
                sender: 'me',
                time: '13:35',
                isRead: true,
            },
        ],
    },
    {
        id: '8',
        username: '김준영',
        profile: 'https://avatar.iran.liara.run/public/31',
        messages: [
            {
                id: '1',
                text: '다음 주에 시간 괜찮으세요?',
                sender: 'other',
                time: '16:45',
                isRead: true,
            },
            {
                id: '2',
                text: '네, 괜찮아요. 무슨 일이세요?',
                sender: 'me',
                time: '16:50',
                isRead: true,
            },
            {
                id: '3',
                text: '다음 프로젝트 계획에 대해 생각 중인데, 피드백이 필요합니다 🥹🥹',
                sender: 'other',
                time: '16:55',
                isRead: false,
            },
            {
                id: '3',
                image: 'https://picsum.photos/id/6/200',
                sender: 'other',
                time: '16:55',
                isRead: false,
            },
        ],
    },
    {
        id: '9',
        username: '송이영',
        profile: 'https://avatar.iran.liara.run/public/90',
        messages: [
            {
                id: '1',
                text: '요즘 어떻게 지내세요?',
                sender: 'other',
                time: '14:00',
                isRead: true,
            },
            {
                id: '2',
                text: '잘 지내고 있어요. 당신은요?',
                sender: 'me',
                time: '14:05',
                isRead: true,
            },
            {
                id: '3',
                text: '요즘에는 취미 생활에 빠져 있어요. 당신의 취미는 무엇인가요?',
                sender: 'other',
                time: '14:10',
                isRead: true,
            },
            {
                id: '4',
                text: '저도 최근에 피아노를 배우고 있어요.',
                sender: 'me',
                time: '14:12',
                isRead: true,
            },
            {
                id: '5',
                image: 'https://picsum.photos/200/300?image=180',
                sender: 'me',
                time: '14:12',
                isRead: true,
            },
        ],
    },
    {
        id: '10',
        username: '조성현',
        profile: 'https://avatar.iran.liara.run/public/40',
        messages: [
            {
                id: '1',
                text: '오늘 회의 참석 들어오시나요?',
                sender: 'other',
                time: '09:00',
                isRead: true,
            },
            {
                id: '2',
                text: '네, 가능합니다!',
                sender: 'me',
                time: '09:05',
                isRead: true,
            },
            {
                id: '3',
                text: '회의 전에 점심 같이 드실래요?',
                sender: 'other',
                time: '09:08',
                isRead: false,
            },
            {
                id: '4',
                text: '오늘 수석님이 갈비집 가자고 하십니다',
                sender: 'other',
                time: '09:08',
                isRead: false,
            },
        ],
    },
];
